import "./globals.css";
import { Inter } from "next/font/google";
import LayoutProvider from "./components/LayoutProvider.jsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider>
          <main>{children}</main>
        </LayoutProvider>
      </body>
    </html>
  );
}
