import "./globals.css";

import LayoutProvider from "./components/LayoutProvider.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LayoutProvider>
          <main>{children}</main>
        </LayoutProvider>
      </body>
    </html>
  );
}
