import "./globals.css";
import "./components/loading.css";
import LayoutProvider from "./components/LayoutProvider.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <LayoutProvider>
          <main style={{ margin: 0, padding: 0 }}>{children}</main>
        </LayoutProvider>
      </body>
    </html>
  );
}
